name=htcw_json
version=0.2.7
author=honey the codewitch
maintainer=honey the codewitch
sentence=Provides JSON parsing
paragraph=Provides a JSON peephole parser
category=Data Processing
depends=htcw_io=(>=1.4.3 && <1.5.0)
url=https://github.com/codewitch-honey-crisis/htcw_io
architectures=*
